### ISSUE TITLE
Inconsistent ExecResult?

### ISSUE THREAD

**Issue by danhyun** [lucastheisen/jsch-nio#19]
When using `UnixSshFileSystemProvider` I'm getting flaky behavior that I've traced down to `statParse(String, SupportedAttribute[])`

What I'm encountering is ArrayIndexOOB exception but when digging in it turns out that `stat --printf` command sometimes returns an empty result for me. Sitting in the debugger with breakpoint on 

```
    private ExecuteResult execute( UnixSshPath path, String command ) throws IOException {
        CommandRunner commandRunner = path.getFileSystem().getCommandRunner();
        try {
            return commandRunner.execute( command );
        }
        catch ( JSchException e ) {
            throw new IOException( e );
        }
    }
```

If I keep evaluating `execute(command)` sometimes I end up with an empty StdOut but with 0 exit result.

I know that this bit of code relies on com.jcraft's jsch lib but I was wondering if you have encountered this and if there are any known work arounds.

If it helps my target machine is running: Linux version 2.6.18.8.xs5.6.0.15.449 (root@skinny-2) (gcc version 4.1.2 20061115 (prerelease) (Debian 4.1.1-21))

**Comment by danhyun** [comment]
Some further debugging reveals that executing the command from my dev machine via ssh works just fine. I'm start to suspect that the jsch library is to blame, it almost feels as if there's a race condition and that the stdout doesn't have time to catch up before jsch returns.

**Comment by lucastheisen** [comment]
@danhyun, I have not run into anything like that before.  Can you create a unit test that can reproduce this?  Perhaps a loop of calls to stat that will eventually exhibit this behavior?

**Comment by danhyun** [comment]
The way in which we interact with the remote system is via the `FileSystem` provided so our test looks like this:

```java
@Test
    public void testUploadDir() throws Exception {
        DefaultSessionFactory sessionFactory = new DefaultSessionFactory(username, null, null);
        sessionFactory.setKnownHosts(this.getClass().getResourceAsStream("/known_hosts"));
        sessionFactory.setPassword(password);
        Map<String, Object> environment = Maps.newHashMap();
        environment.put("defaultSessionFactory", sessionFactory);
        environment.put("watchservice.inotify", true);
        String subDir = "/tmp/sftp/";

        FileSystem fs = FileSystems.newFileSystem(
                new URI(uriGenerator.apply(subDir)),
                environment);
        
        Path remotePath = fs.getPath("test");
        Files.walkFileTree(remotePath, new SimpleFileVisitor<Path>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                Files.deleteIfExists(file);
                return FileVisitResult.CONTINUE;
            }

            @Override
            public FileVisitResult postVisitDirectory(Path dir, IOException exc) throws IOException {
                Files.delete(dir);
                return FileVisitResult.CONTINUE;
            }
        });
        Files.deleteIfExists(remotePath);

        //Recursive copy
        Path localPath = Paths.get("C:/tmp/test/");
        
        Files.walkFileTree(localPath, new SimpleFileVisitor<Path>(){
            @Override
            public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
                Path targetPath = remotePath.resolve(localPath.relativize(dir));
                if (!Files.exists(targetPath)) {
                    Files.createDirectory(targetPath);
                }
                return FileVisitResult.CONTINUE;
            }

            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                Files.copy(file, remotePath.resolve(localPath.relativize(file)));
                return FileVisitResult.CONTINUE;
            }
        });
    }
```


```
11:27:21.080 [main] DEBUG c.pastdev.jsch.command.CommandRunner - executing stat --printf "%W %i %F %F %F %F %X %Y %s" "/tmp/sftp/test" on ssh://user@host:22

java.lang.ArrayIndexOutOfBoundsException: 1

	at com.pastdev.jsch.nio.file.UnixSshFileSystemProvider.statParse(UnixSshFileSystemProvider.java:648)
	at com.pastdev.jsch.nio.file.UnixSshFileSystemProvider.readAttributes(UnixSshFileSystemProvider.java:541)
	at com.pastdev.jsch.nio.file.UnixSshFileSystemProvider.access$600(UnixSshFileSystemProvider.java:62)
	at com.pastdev.jsch.nio.file.UnixSshFileSystemProvider$BasicFileAttributesImpl.<init>(UnixSshFileSystemProvider.java:762)
	at com.pastdev.jsch.nio.file.UnixSshFileSystemProvider$BasicFileAttributesImpl.<init>(UnixSshFileSystemProvider.java:749)
	at com.pastdev.jsch.nio.file.UnixSshFileSystemProvider$BasicFileAttributesImpl.<init>(UnixSshFileSystemProvider.java:741)
	at com.pastdev.jsch.nio.file.UnixSshFileSystemProvider.readAttributes(UnixSshFileSystemProvider.java:498)
```

It blows up pretty quickly

**Comment by danhyun** [comment]
Note when I execute from command line I fail to produce an empty output:

```
$ ssh user@host 'stat --printf "%W %i %F %F %F %F %X %Y %s" "/tmp/sftp/test"'
W 148393 directory directory directory directory 1465485068 1465485072 4096
```

**Comment by danhyun** [comment]
This seems to be an issue with my server, I've reprovisioned it and the issue seems to be gone.
